# Generated by Django 3.0.8 on 2020-07-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200720_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='street',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='zipcode',
            field=models.CharField(default='34223', max_length=5, verbose_name='zip code'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
