# Generated by Django 3.0.8 on 2020-07-21 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v2_interface', '0002_notficiation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmPickUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('pick_up', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v2_interface.PickUpV2')),
            ],
        ),
        migrations.CreateModel(
            name='PickUpReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('pick_up', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v2_interface.PickUpV2')),
            ],
        ),
        migrations.DeleteModel(
            name='Notficiation',
        ),
    ]
