# Generated by Django 3.0.8 on 2020-07-21 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('v2_interface', '0003_auto_20200721_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmpickup',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickupreminder',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
