# Generated by Django 3.0.8 on 2020-07-20 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waste_bins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='scheduled_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pickup',
            name='scheduled_date',
            field=models.DateField(),
        ),
    ]
