# Generated by Django 3.0.8 on 2020-07-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_bins', '0004_auto_20200720_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
