# Generated by Django 3.0.8 on 2020-07-20 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste_bins', '0005_pickup_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickup',
            name='scheduled_time',
        ),
    ]
